apiVersion: v1
kind: Secret
metadata:
  name:  "{{ .Release.Name }}-env"
  labels:
{{ include "tezos.labels" . | indent 4 }}
type: Opaque
data:
  DATA_DIR: {{ .Values.tezos.base_path | b64enc }}
  NODE_RPC_PORT: {{ .Values.service.rpcPort | b64enc }}
  NODE_HOST: {{ "localhost" | b64enc }}
